# Bilinear Transcoding with hidden_multiplier sweep
sweep:
  parameter: transcoding.hidden_multiplier
  values: [0.25, 0.5, 1.0, 2.0, 4.0]

config:
  model:
    name: "EleutherAI/pythia-410m"
    device: "cuda"

  dataset:
    name: "monology/pile-uncopyrighted"
    split: "train"
    max_length: 128

  transcoding:
    layer_idx: 3
    model_type: "Bilinear"
    optimizer_type: "Muon"
    batch_size: 512
    learning_rate: 0.02
    hidden_multiplier: null  # Will be set from sweep
    bias: true
    debug: true
    n_batches: 20
    n_batches_full: 500
